import React from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { SiteFooter } from '@/components/shared/SiteFooter';

export default function RefundPolicy() {
  const lastUpdated = "May 11, 2026";

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col"><div className="flex-1 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white shadow-sm rounded-lg overflow-hidden border border-gray-100">
        <div className="px-6 py-8 sm:p-10">
          {/* Back Button */}
          <Link 
            href="/"
            className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 mb-6 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
          
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Refund Policy</h1>
          <p className="text-gray-500 text-sm mb-8">Last Updated: {lastUpdated}</p>

          <div className="space-y-8 text-gray-700 leading-relaxed text-sm sm:text-base">
            
            {/* Section 1: Introduction */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">1. Introduction</h2>
              <p className="mb-4">
                At Hired, we strive to provide high-quality resume optimization services. 
                This Refund Policy outlines the terms and conditions under which refunds may be issued 
                for our services.
              </p>
              <div className="bg-green-50 border-2 border-green-500 rounded-lg p-4">
                <p className="text-green-900 font-semibold text-base">
                  ✅ 14-Day Money-Back Guarantee
                </p>
                <p className="text-green-800 mt-2">
                  We are committed to your satisfaction. If you're not happy with our service, 
                  you can request a full refund within 14 days of your purchase, no questions asked.
                </p>
              </div>
            </section>

            {/* Section 2: Service Nature */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">2. Nature of Service</h2>
              <p className="mb-3">
                Our Service provides AI-powered resume analysis and optimization. Please note:
              </p>
              <ul className="list-disc list-outside ml-5 space-y-2 bg-blue-50 p-4 rounded-md border border-blue-100 text-gray-800">
                <li>
                  <strong>Digital Service:</strong> Our service is delivered immediately upon completion 
                  of the optimization process. Once you receive your optimized resume, the service has been rendered.
                </li>
                <li>
                  <strong>AI-Generated Content:</strong> The optimized content is generated by AI and 
                  requires your review and verification before use.
                </li>
                <li>
                  <strong>No Job Guarantee:</strong> We do not guarantee job interviews, offers, or employment 
                  as a result of using our service.
                </li>
              </ul>
            </section>

            {/* Section 3: Refund Eligibility */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">3. 14-Day Money-Back Guarantee</h2>
              <p className="mb-3">
                <strong>We offer a 14-day money-back guarantee on all credit purchases.</strong> 
                You may request a full refund within 14 days of your purchase for any reason, including:
              </p>
              <ul className="list-disc list-outside ml-5 space-y-2">
                <li>
                  <strong>Not Satisfied:</strong> If you're not happy with the quality of our AI optimization service.
                </li>
                <li>
                  <strong>Service Not Delivered:</strong> If the optimization service fails to complete 
                  due to a technical error on our end.
                </li>
                <li>
                  <strong>Duplicate Charges:</strong> If you were charged multiple times for a single purchase.
                </li>
                <li>
                  <strong>Processing Errors:</strong> If a payment was processed in error.
                </li>
                <li>
                  <strong>Changed Your Mind:</strong> If you simply decide you don't want to use the service.
                </li>
              </ul>
              <p className="mt-3 bg-yellow-50 border border-yellow-200 rounded-lg p-3 text-sm">
                <strong>Important:</strong> Refund requests must be submitted within 14 days of purchase. 
                After 14 days, refunds will be evaluated on a case-by-case basis.
              </p>
            </section>

            {/* Section 4: After 14-Day Period */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">4. After 14-Day Period</h2>
              <p className="mb-3">
                After the 14-day guarantee period, refunds may still be considered in exceptional circumstances:
              </p>
              <ul className="list-disc list-outside ml-5 space-y-2">
                <li>
                  <strong>Technical Issues:</strong> Persistent technical problems that prevent service use.
                </li>
                <li>
                  <strong>Unauthorized Charges:</strong> Charges made without your authorization.
                </li>
                <li>
                  <strong>Billing Errors:</strong> Incorrect amounts charged or duplicate transactions.
                </li>
              </ul>
              <p className="mt-3 text-sm text-gray-600">
                Note: We do not guarantee job interviews, offers, or employment outcomes. 
                Refunds will not be issued based solely on employment results.
              </p>
            </section>

            {/* Section 5: Refund Process */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">5. How to Request a Refund</h2>
              <p className="mb-3">
                To request a refund within the 14-day guarantee period, please contact our support team. 
                Include the following information:
              </p>
              <ul className="list-disc list-outside ml-5 space-y-2">
                <li>Your account email address</li>
                <li>Polar order ID or receipt email</li>
                <li>Date of purchase</li>
                <li>Brief reason for refund (optional for requests within 14 days)</li>
              </ul>
              <div className="mt-4 bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="font-semibold text-blue-900 mb-2">Refund Timeline:</p>
                <ul className="space-y-1 text-blue-800 text-sm">
                  <li>• <strong>Within 14 days:</strong> Instant approval, no questions asked</li>
                  <li>• <strong>Review time:</strong> 1-2 business days</li>
                  <li>• <strong>Processing time:</strong> 5-10 business days to your original payment method</li>
                </ul>
              </div>
            </section>

            {/* Section 6: Subscription Services */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">6. Subscription Services</h2>
              <p>
                If you have a subscription, you may cancel at any time. Cancellation will take effect at the end 
                of your current billing period. No refunds will be issued for the current billing period, 
                but you will continue to have access to the service until the period ends.
              </p>
            </section>

            {/* Section 7: Chargebacks */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">7. Chargebacks</h2>
              <p>
                If you initiate a chargeback or dispute a charge, we reserve the right to suspend or terminate 
                your account. We encourage you to contact us directly first to resolve any issues before 
                initiating a chargeback.
              </p>
            </section>

            {/* Section 8: Changes to Policy */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">8. Changes to This Policy</h2>
              <p>
                We reserve the right to modify this Refund Policy at any time. Changes will be effective 
                immediately upon posting on this page. Your continued use of the Service after changes 
                constitutes acceptance of the updated policy.
              </p>
            </section>

            <div className="mt-12 pt-8 border-t border-gray-200">
              <div className="text-center">
                <p className="text-xs text-gray-500 mb-4">
                  For refund requests or questions about this policy, please contact our support team.
                </p>
                <a
                  href="https://tally.so/r/Zjaz0a"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center px-6 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm hover:shadow-md"
                >
                  Contact Support Team
                </a>
              </div>
            </div>

          </div>
        </div>
      </div>
      </div>
      <SiteFooter />
    </div>
  );
}
