import React from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function RefundPolicy() {
  const lastUpdated = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white shadow-sm rounded-lg overflow-hidden border border-gray-100">
        <div className="px-6 py-8 sm:p-10">
          {/* Back Button */}
          <Link 
            href="/"
            className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 mb-6 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
          
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Refund Policy</h1>
          <p className="text-gray-500 text-sm mb-8">Last Updated: {lastUpdated}</p>

          <div className="space-y-8 text-gray-700 leading-relaxed text-sm sm:text-base">
            
            {/* Section 1: Introduction */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">1. Introduction</h2>
              <p>
                At Hired CV, we strive to provide high-quality resume optimization services. 
                This Refund Policy outlines the terms and conditions under which refunds may be issued 
                for our services.
              </p>
            </section>

            {/* Section 2: Service Nature */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">2. Nature of Service</h2>
              <p className="mb-3">
                Our Service provides AI-powered resume analysis and optimization. Please note:
              </p>
              <ul className="list-disc list-outside ml-5 space-y-2 bg-blue-50 p-4 rounded-md border border-blue-100 text-gray-800">
                <li>
                  <strong>Digital Service:</strong> Our service is delivered immediately upon completion 
                  of the optimization process. Once you receive your optimized resume, the service has been rendered.
                </li>
                <li>
                  <strong>AI-Generated Content:</strong> The optimized content is generated by AI and 
                  requires your review and verification before use.
                </li>
                <li>
                  <strong>No Job Guarantee:</strong> We do not guarantee job interviews, offers, or employment 
                  as a result of using our service.
                </li>
              </ul>
            </section>

            {/* Section 3: Refund Eligibility */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">3. Refund Eligibility</h2>
              <p className="mb-3">Refunds may be considered in the following circumstances:</p>
              <ul className="list-disc list-outside ml-5 space-y-2">
                <li>
                  <strong>Service Not Delivered:</strong> If the optimization service fails to complete 
                  due to a technical error on our end, you may be eligible for a full refund.
                </li>
                <li>
                  <strong>Duplicate Charges:</strong> If you were charged multiple times for a single 
                  service, we will refund the duplicate charges.
                </li>
                <li>
                  <strong>Processing Errors:</strong> If a payment was processed in error, we will issue 
                  a full refund upon verification.
                </li>
              </ul>
            </section>

            {/* Section 4: Non-Refundable Situations */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">4. Non-Refundable Situations</h2>
              <p className="mb-3">Refunds will generally not be issued in the following cases:</p>
              <ul className="list-disc list-outside ml-5 space-y-2">
                <li>If the service was successfully completed and delivered</li>
                <li>If you are dissatisfied with the AI-generated content (as it requires your review and editing)</li>
                <li>If you did not receive job interviews or offers (we do not guarantee employment outcomes)</li>
                <li>If you changed your mind after the service was rendered</li>
                <li>If the issue is due to user error (e.g., incorrect file upload, wrong job description)</li>
              </ul>
            </section>

            {/* Section 5: Refund Process */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">5. Refund Request Process</h2>
              <p className="mb-3">
                To request a refund, please contact our support team through our contact form. 
                Include the following information:
              </p>
              <ul className="list-disc list-outside ml-5 space-y-2">
                <li>Your account email or transaction ID</li>
                <li>Date of purchase</li>
                <li>Reason for refund request</li>
                <li>Any relevant documentation or screenshots</li>
              </ul>
              <p className="mt-3">
                We will review your request within 5-7 business days and notify you of our decision. 
                If approved, refunds will be processed to the original payment method within 10-14 business days.
              </p>
            </section>

            {/* Section 6: Subscription Services */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">6. Subscription Services</h2>
              <p>
                If you have a subscription, you may cancel at any time. Cancellation will take effect at the end 
                of your current billing period. No refunds will be issued for the current billing period, 
                but you will continue to have access to the service until the period ends.
              </p>
            </section>

            {/* Section 7: Chargebacks */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">7. Chargebacks</h2>
              <p>
                If you initiate a chargeback or dispute a charge, we reserve the right to suspend or terminate 
                your account. We encourage you to contact us directly first to resolve any issues before 
                initiating a chargeback.
              </p>
            </section>

            {/* Section 8: Changes to Policy */}
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">8. Changes to This Policy</h2>
              <p>
                We reserve the right to modify this Refund Policy at any time. Changes will be effective 
                immediately upon posting on this page. Your continued use of the Service after changes 
                constitutes acceptance of the updated policy.
              </p>
            </section>

            <div className="mt-12 pt-8 border-t border-gray-200">
              <div className="text-center">
                <p className="text-xs text-gray-500 mb-4">
                  For refund requests or questions about this policy, please contact our support team.
                </p>
                <a
                  href="https://tally.so/r/Zjaz0a"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center px-6 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm hover:shadow-md"
                >
                  Contact Support Team
                </a>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
